.PHONY: run run-debug

run:
	~/workspace/go/src/osdrv/liss/liss -src ./main.liss

run-debug:
	~/workspace/go/src/osdrv/liss/liss -debug -src ./main.liss

run-pprof:
	~/workspace/go/src/osdrv/liss/liss -debug -pprof -src ./main.liss
